### PR TITLE
Replace PBKDF2 with Argon2id

### PR DESCRIPTION
**Pull request by umutcamliyurt**

### CODE REVIEW

**Comment by zorggomat** [comment]
Hello, @umutcamliyurt!
I find your suggestions very interesting.
Please let me know if you continue to work on your proposal and plan to reopen it.
I am very pleased with your attention to this project.

**Comment by umutcamliyurt** [comment]
Hello,
Thank you for your interest and positive feedback. I appreciate your kind words.
Yes, I plan to continue working on the proposal and make improvements as necessary. I will definitely keep you informed about any progress and plans to reopen this.

**Comment by umutcamliyurt** [comment]
I am still interested, thank you

**Comment by umutcamliyurt** [comment]
@zorggomat give me your e-mail so we can exchange ideas

**Pull request closed without merging**
